### ISSUE TITLE
Set Go Redis V8 Client Problem

### ISSUE THREAD

**Issue by cyberbeast** [nitishm/go-rejson#47]
Hi,

I wanted to report incompatibilities with v8 of go-redis. According to `go-redis` documentation, v8 is the latest recommended version.

Very similar to the issue concerning upgrading from go-redis v6 to v7.

**Comment by cyberbeast** [comment]
Please see PR #46 for the fix.

**Comment by Shivam010** [comment]
Hello @cyberbeast, thanks for the PR.

I have left some reviews and suggestions in the PR. Feel free to share your thoughts on them, I'll happy to discuss them.

**Comment by Shivam010** [comment]
@cyberbeast I have added some changes in your PR and have merged it.
A new version has been released with the concerned support [v4.0.0](https://github.com/nitishm/go-rejson/releases/tag/v4.0.0)
