### ISSUE TITLE
Plans on supporting go-redis v9?

### ISSUE THREAD

**Issue by tgbv** [nitishm/go-rejson#74]
Are there plans on adding support for go-redis v9? (github.com/redis/go-redis/v9)

**Comment by Shivam010** [comment]
Hey @tgbv 👋

We already support `redis/go-redis/v9`

Here's the example https://github.com/nitishm/go-rejson/blob/master/examples/json_set/json_set.go#L11 

If you're asking for something different, please elaborate.
